### PR TITLE
Add VueJS Ouagadougou

### PR DESCRIPTION
**Pull request by Xsmael**
Dear @bencodezen  and core team,

Ouagadougou is the Capital city of Burkina Faso, a Beautiful country right in the middle of West Africa with lots of challenges and opportunities. We have started meetups last year, and we have  meetings twice a month to help beginners to get started with the framework, and frontend dev in general.

Please Kindly review and accept my PR, or let me know if any correction needed.

By the way, what do you think of a Vue App to update these lists, instead of relying on github ?

Thanks!

### CODE REVIEW

**Comment by Xsmael** [comment]
Hello!  Anyone ??

**Comment by Xsmael** [comment]
@bencodezen  Hallo ^^'

**Review by bencodezen — APPROVED** [review]
Thank you for the PR! Apologies for the delay in getting to this. Appreciate the work you're doing in Ouagadougou!

**Comment by Xsmael** [comment]
Gracias! :)

**Pull request merged**
