### PR TITLE
Update 2019-cfps.json

### PR DESCRIPTION
**Pull request by Stegosource**

### CODE REVIEW

**Comment by bencodezen** [comment]
Hey @Stegosource. It looks like we have some issues with the checks. Not sure what's going on, but let me know if you have a chance to look at it. Otherwise I can close this and issue a separate PR.

**Comment by Stegosource** [comment]
@bencodezen sorry about that. I made the patch quickly through the GitHub editor, but after looking the in Netlify logs I found the culprit; an extra comma in the JSON. I think everything should be good to go at this point.

**Comment by gustojs** [comment]
@Stegosource yes, that would be preferable to put them to "inactive", so that we have track of the events. Thank you and sorry for taking so much time.

**Comment by Stegosource** [comment]
@gustojs I just finished returning the old events and placing them in the inactive array. Not sure what's up with the white space, but everything seems to be working fine.

**Comment by bencodezen** [comment]
Thanks for the update @Stegosource!

**Comment by Stegosource** [comment]
No problem @bencodezen. Actually I just saw two new RFPs today, so I'll be updating and making a new PR soon ;)

**Pull request merged**
